telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 379, in _network_loop_retry
    if not action_cb():
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 340, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 2138, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 248, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 379, in _network_loop_retry
    if not action_cb():
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 340, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 2138, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 248, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 379, in _network_loop_retry
    if not action_cb():
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 340, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 2138, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 248, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 379, in _network_loop_retry
    if not action_cb():
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 340, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 2138, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 248, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 379, in _network_loop_retry
    if not action_cb():
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 340, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/bot.py", line 2138, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
    **urlopen_kwargs)
  File "/home/maxim/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 248, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
