telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/maximreutov/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "botik.py", line 24, in message_handler
    chat_id = update.message.chat.id
AttributeError: 'NoneType' object has no attribute 'chat'
